### ISSUE TITLE
Cannot install it in vaadin

### ISSUE THREAD

**Issue by russellhoff** [mikrop/v-leaflet-easyprint-parent#1]
When adding the dependency to my ivy.xml file, the following mesagge crops up:

I can't install it: Some projects fail to be resolved Impossible to resolve dependencies of com.ingartek.cavwebapp#v7proj;working@IN006-PC unresolved dependency: org.vaadin.addons#g-leaflet-easyprint;1.0.0: not found

**Comment by mstahv** [comment]
@mikrop, I think the issue here is that the gwt module (g-leaflet-easyprint) is not uploaded to vaadin.com/directory . Would you upload the plain gwt module to the directory as well? I'm pretty sure it is in you local maven repository.

**Comment by mikrop** [comment]
@mstahv, Thank you for your cooperation. I uploaded g-leaflet-easyprint of my add-ons https://vaadin.com/directory#!addon/g-leaflet-easyprint and the error is resolved. I checked after cleaning the local .m2
